
name: 部署文档

on:
  push:
    branches:
      # 确保这是你正在使用的分支名称
      - main

jobs:
  deploy-gh-pages:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          # 如果你文档需要 Git 子模块，取消注释下一行
          # submodules: true



      - name: 设置 Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: npm

      - name: 安装依赖
        run: npm install

      - name: 构建文档
        env:
          NODE_OPTIONS: --max_old_space_size=4096
        run: npm run docs:clean-dev && npm run docs:build

      - name: 部署文档
        uses: peaceiris/actions-gh-pages@v3
        with:
          deploy_key: ${{ secrets.fsyblog }}
          external_repository: fsy-1209/fsy-1209.github.io
          # 这是文档部署到的分支名称
          publish_branch: main
          publish_dir: docs/.vuepress/dist

